# Generated by Django 2.0.3 on 2018-03-18 13:25

from django.db import migrations, models
import image_processing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[image_processing.models.check_dimensions])),
                ('progress', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
